export const sessions = [
    {
        id: 1,
        workoutId: 1,
        name: 'Push ups',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: 'done',
    },
    {
        id: 2,
        workoutId: 1,
        name: 'Exercise 2',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '4 mins.',
        weights: 0,
        status: null,
    },
    {
        id: 3,
        workoutId: 1,
        name: 'Exercise 3',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: 'current',
    },
    {
        id: 4,
        workoutId: 1,
        name: 'Exercise 4',
        pictureUrl: 'workout.jpg',
        repetitions: 20,
        duration: '5 mins.',
        weights: 0,
        status: 'done',
    },
    {
        id: 5,
        workoutId: 2,
        name: 'Exercise 1',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: 'done',
    },
    {
        id: 6,
        workoutId: 2,
        name: 'Exercise 2',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: 'done',
    },
    {
        id: 7,
        workoutId: 2,
        name: 'Exercise 3',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: null,
    },
    {
        id: 8,
        workoutId: 3,
        name: 'Exercise 1',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: 'current',
    },
    {
        id: 9,
        workoutId: 3,
        name: 'Exercise 2',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: 'done',
    },
    {
        id: 10,
        workoutId: 3,
        name: 'Exercise 3',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: null,
    },
    {
        id: 11,
        workoutId: 3,
        name: 'Exercise 4',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: 'done',
    },
    {
        id: 12,
        workoutId: 4,
        name: 'Exercise 1',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: null,
    },
    {
        id: 13,
        workoutId: 4,
        name: 'Exercise 2',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: null,
    },
    {
        id: 14,
        workoutId: 4,
        name: 'Exercise 3',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: null,
    },
    {
        id: 15,
        workoutId: 4,
        name: 'Exercise 4',
        pictureUrl: 'workout.jpg',
        repetitions: 10,
        duration: '5 mins.',
        weights: 0,
        status: null,
    },
];