import { Workout } from "../Home/Home";

export const workouts: Workout[] = [
    {   
        id: 1,
        name: 'Abs',
        duration: '30 mins.', 
        type: 'Upper body', 
        status: 'UNCOMPLETED',
        iconUrl: 'bench-press.png',
    },
    {   
        id: 2,
        name: 'Arms', 
        duration: '25 mins.', 
        type: 'Upper body', 
        status: 'COMPLETED',
        iconUrl: 'bench-press.png',
    },
    {   
        id: 3,
        name: 'Back', 
        duration: '20 mins.', 
        type: 'Upper body', 
        status: 'UNCOMPLETED',
        iconUrl: 'bench-press.png',
    },
    {   
        id: 4,
        name: 'Calves', 
        duration: '15 mins.', 
        type: 'Lower body', 
        status: 'UNCOMPLETED',
        iconUrl: 'bench-press.png',
    },
    {   
        id: 5,
        name: 'Chest', 
        duration: '44 mins.', 
        type: 'Upper body', 
        status: 'UNCOMPLETED',
        iconUrl: 'bench-press.png',
    },
    {   
        id: 6,
        name: 'Legs', 
        duration: '23 mins.', 
        type: 'Lower body', 
        status: 'UNCOMPLETED',
        iconUrl: 'bench-press.png',
    },
    {   
        id: 7,
        name: 'Shoulders', 
        duration: '19 mins.', 
        type: 'Upper body', 
        status: 'UNCOMPLETED',
        iconUrl: 'bench-press.png',
    },
]